#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

typedef struct ins {
	int c;
	int d;
	int mD;
	int mE;
	int wait;
} ins;

ins seq[4]; //CHANGEME
int seqindex = 0;
int last = 3; //CHANGEME

void dins(int i, int c, int d, int mD, int mE, int wait) {
	seq[i].c = c;
	seq[i].d = d;
	seq[i].mD = mD;
	seq[i].mE = mE;
	seq[i].wait = wait;
}

task main()
{
  dins(0, 150, 100, 0, 0, 100);
  dins(1, 150, 100, 25, 25, 350);
	//dins(2, 150, 100, 0, 25, 100);
	//dins(3, 150, 100, 25, 25, 100);

  waitForStart(); // Wait for the beginning of autonomous phase.

  while (1) {
	  servo[servo1] = seq[seqindex].c;
	  servo[servo2] = seq[seqindex].d;
    motor[motorD] = seq[seqindex].mD;
    motor[motorE] = -(seq[seqindex].mE);

	  wait10Msec(seq[seqindex].wait);
    ++seqindex;
    if (seqindex > last) {
    	break;
    }
	}
}
